import { CommonModule } from '@angular/common';
import {
  ChangeDetectionStrategy,
  Component,
  EventEmitter,
  Input,
  NgModule,
  Output,
} from '@angular/core';
import { MarkdownBlock } from '@marmicode/block-core';
import { HighlightZone } from '../highlight/highlight-zone';
import { MarkdownBlockStateService } from './markdown-block-state.service';
import { MarkdownModule } from './markdown.module';

@Component({
  changeDetection: ChangeDetectionStrategy.OnPush,
  selector: 'mc-markdown-block',
  template: `<mc-markdown-tokens
    [tokens]="block.tokens"
    (highlightZoneChange)="onHighlightZoneChange($event)"
  ></mc-markdown-tokens>`,
  styles: [
    `
      :host {
        display: block;
        margin: 10px;

        color: #292929;
        font-family: Georgia, 'Times New Roman', Times, serif;
        font-weight: 400;
        text-rendering: optimizeLegibility;
        word-break: break-word;
        -webkit-font-smoothing: antialiased;

        font-size: 18px;
        line-height: 28px;
      }

      @media (min-width: 960px) {
        :host {
          font-size: 21px;
          line-height: 31px;
        }
      }
    `,
  ],
  providers: [MarkdownBlockStateService],
})
export class MarkdownBlockComponent {
  @Input() block: MarkdownBlock;

  /**
   * The available zones to highlight.
   */
  @Input() set highlightableZones(highlightableZones: HighlightZone[]) {
    this._markdownBlockStateService.setHighlightableZones(highlightableZones);
  }

  @Output() highlightZoneChange = new EventEmitter<HighlightZone>();

  constructor(private _markdownBlockStateService: MarkdownBlockStateService) {}

  /**
   * Convert custom event (generated by `<mc-highlight-link>`) to Angular output.
   */
  onHighlightZoneChange($event: CustomEvent<HighlightZone>) {
    $event.stopImmediatePropagation();
    this.highlightZoneChange.emit($event.detail);
  }
}

@NgModule({
  declarations: [MarkdownBlockComponent],
  exports: [MarkdownBlockComponent],
  imports: [CommonModule, MarkdownModule],
})
export class MarkdownBlockModule {}
