schema:
  - https://graphql.contentful.com/content/v1/spaces/gowvxq3b4aid/environments/master?token=_d7Vb4r2lborp1uLTvsv0ne7fB0OMez2FscTnHQux5A:
      headers:
        Authorization: Bearer _d7Vb4r2lborp1uLTvsv0ne7fB0OMez2FscTnHQux5A
extensions:
  codegen:
    generates:
      ./libs/resource-feature-search/src/lib/graphql/schema.graphql:
        plugins:
          - schema-ast
      ./libs/resource-feature-search/src/lib/graphql/schema.ts:
        plugins:
          - typescript
        config:
          declarationKind: 'interface'
