schema:
  - https://graphql.contentful.com/content/v1/spaces/gowvxq3b4aid/environments/master:
      headers:
        Authorization: Bearer _d7Vb4r2lborp1uLTvsv0ne7fB0OMez2FscTnHQux5A
extensions:
  codegen:
    generates:
      ./libs/contentful-api/src/lib/schema.graphql:
        plugins:
          - schema-ast
      ./libs/contentful-api/src/lib/schema.ts:
        plugins:
          - typescript
        config:
          declarationKind: 'interface'
