yarnPath: .yarn/releases/yarn-3.3.0.cjs

defaultSemverRangePrefix: ""

packageExtensions:
  "nx@*":
    dependencies:
      "@angular-devkit/core": "*"
  "jest-preset-angular@*":
    dependencies:
      "jest-util": "*"