defaultSemverRangePrefix: ''

packageExtensions:
  '@google-cloud/pubsub@*':
    dependencies:
      '@grpc/grpc-js': '*'
  firebase-tools@*:
    dependencies:
      exegesis: '*'
      winston-transport: '*'
  jest-preset-angular@*:
    dependencies:
      jest-util: '*'
  '@angular-eslint/eslint-plugin-template@*':
    dependencies:
      '@typescript-eslint/types': '*'

yarnPath: .yarn/releases/yarn-3.5.1.cjs
