yarnPath: .yarn/releases/yarn-3.3.0.cjs

nodeLinker: node-modules

defaultSemverRangePrefix: ''

packageExtensions:
  '@google-cloud/pubsub@*':
    dependencies:
      '@grpc/grpc-js': '*'
  'firebase-tools@*':
    dependencies:
      'winston-transport': '*'
  'jest-preset-angular@*':
    dependencies:
      'jest-util': '*'