module.exports = {
  projects: [
    '<rootDir>/apps/marmicode',
    '<rootDir>/libs/blog-post-feature-detail',
    '<rootDir>/libs/blog-post-ui',
    '<rootDir>/libs/contentful-api',
    '<rootDir>/libs/frame-api',
    '<rootDir>/libs/frame-core',
    '<rootDir>/libs/frame-ui',
    '<rootDir>/libs/learning-map-feature-tree',
    '<rootDir>/libs/recipe-feature-detail',
    '<rootDir>/libs/resource-api',
    '<rootDir>/libs/resource-core',
    '<rootDir>/libs/resource-feature-search',
    '<rootDir>/libs/services-feature-presentation',
    '<rootDir>/libs/shared-router-helpers',
    '<rootDir>/libs/shared-ui',
    '<rootDir>/libs/shared-utils',
  ],
};
