name: Test & Deploy

concurrency: ci-${{ github.ref }}

on:
  pull_request: {}
  push:
    branches:
      - main
  # Allow manual trigger.
  workflow_dispatch: {}

x-steps:
  cache: &cache
    uses: actions/cache@v3
    with:
      path: |
        ~/.cache/Cypress
        .angular
        .yarn/unplugged
        libs/*/.angular
        node_modules/.cache
      key: cache

  checkout: &checkout
    uses: actions/checkout@v3
    with:
      # Checkout tags so we can use 'affected:* --base=deployed/marmicode-next'
      fetch-depth: 0

  push: &push
    name: Push changes
    uses: ad-m/github-push-action@master
    with:
      github_token: ${{ secrets.GITHUB_TOKEN }}
      branch: ${{ github.ref }}
      force: true
      tags: true

  setup-node: &setup-node
    uses: actions/setup-node@v3
    with:
      cache: yarn
      node-version: '18'

  upload-dist-on-failure: &upload-dist-on-failure
    name: Upload dist (Cypress videos / build output etc...) on failure
    uses: actions/upload-artifact@v2
    if: failure()
    with:
      name: dist
      path: dist

  yarn-install: &yarn-install
    name: Install
    run: yarn install --immutable

x-deploy-base: &deploy-base
  if: github.ref == 'refs/heads/main'
  runs-on: ubuntu-latest
  needs:
    - build
    - lint
    - test
    - ct
    - e2e
    - upload-percy-snapshots

x-percy-env: &percy-env
  PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
  # The full token is used by `percy-poller`.
  # You can find it here https://percy.io/api/v1/tokens after signing-in to Percy as an admin.
  PERCY_FULL_TOKEN: ${{ secrets.PERCY_FULL_TOKEN }}

jobs:
  build:
    name: 📦 Build
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *cache
      - *setup-node
      - *yarn-install
      - name: Build
        run: yarn affected --target=prerender --configuration next --base=deployed/marmicode-next

  lint:
    name: 🧹 Lint
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *cache
      - *setup-node
      - *yarn-install
      - name: Lint
        run: yarn affected --target=lint --base=deployed/marmicode-next

  test:
    name: ✅ Test
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *setup-node
      - *cache
      - *yarn-install
      - name: Test
        run: yarn affected --target=test --base=deployed/marmicode-next

  ct:
    name: ✅ Component Tests
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *cache
      - *setup-node
      - *yarn-install

      - name: Affected Component Tests
        if: github.ref != 'refs/heads/main'
        run: yarn nx affected --target=component-test --parallel 1 --base=deployed/marmicode-next

      - name: All Component Tests
        if: github.ref == 'refs/heads/main'
        run: yarn nx run-many --target=component-test --parallel 1

      - *upload-dist-on-failure

  e2e:
    name: ✅ End to End
    runs-on: ubuntu-latest
    steps:
      - *checkout
      - *cache
      - *setup-node
      - *yarn-install

      - name: Affected E2E
        if: github.ref != 'refs/heads/main'
        run: yarn nx affected --target=e2e --parallel 1 --base=deployed/marmicode-next

      - name: All E2E
        if: github.ref == 'refs/heads/main'
        run: yarn nx run-many --target=e2e --parallel 1

      - *upload-dist-on-failure

  upload-percy-snapshots:
    name: 📸 Upload Percy Snapshots
    runs-on: ubuntu-latest
    env: *percy-env
    needs:
      - ct
      - e2e
    steps:
      - *checkout
      - *cache
      - *setup-node
      - *yarn-install

      - name: Upload Percy Snapshots
        if: github.ref != 'refs/heads/main'
        run: yarn nx affected --target=upload-percy-snapshots --base=deployed/marmicode-next

      - name: Upload All Percy Snapshots
        if: github.ref == 'refs/heads/main'
        run: yarn nx run-many --target=upload-percy-snapshots

      - name: Finalize Percy
        run: yarn percy build:finalize

      # Check Percy Review on main branch only.
      # On other branches, we'll let Percy status check do the job.
      - name: Check Percy Review
        if: github.ref == 'refs/heads/main'
        run: PERCY_TOKEN=$PERCY_FULL_TOKEN yarn percy build:wait --project marmicode/marmicode --fail-on-changes

  deploy-marmicode-next:
    <<: *deploy-base
    name: 🚀 Marmicode Next
    environment:
      name: Marmicode Next
      url: https://marmicode-next.web.app
    steps:
      - *checkout
      - *cache
      - *setup-node
      - *yarn-install
      - name: Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: yarn nx run marmicode:deploy:next
      - name: Tag deployed/marmicode-next
        run: git tag -f deployed/marmicode-next
      - *push
      - *upload-dist-on-failure

  deploy-marmicode:
    <<: *deploy-base
    name: 🚀 Marmicode
    environment:
      name: Marmicode
      url: https://marmicode.io
    steps:
      - *checkout
      - *cache
      - *setup-node
      - *yarn-install
      - name: Deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: yarn nx run marmicode:deploy:production
      - name: Tag deployed/marmicode
        run: git tag -f deployed/marmicode
      - *push
      - *upload-dist-on-failure
