name: Marmicode

on:
  push:
    branches:
      - master
    tags:
      - latest

jobs:

  # Merging all steps in one job might look dirty but this is a way of achieving
  # faster workflows as downloading node_modules cache takes 40 seconds
  # lint & test parallelization is not worth it.
  test-and-deploy:
    runs-on: ubuntu-latest
    env:
      CYPRESS_CACHE_FOLDER: node_modules/.cache/cypress
    steps:
      - name: Increase file watchers to avoid storybook warnings
        run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Get project name
        id: project
        run: |
          PROJECT=$([ $GITHUB_REF == 'refs/tags/latest' ] && echo marmicode || echo marmicode-next)
          echo "::set-output name=project::$PROJECT"
      - uses: actions/checkout@v2
        with:
          # Checkout tags so we can use 'affected:* --base=latest'
          fetch-depth: 0
      - uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - uses: actions/cache@v1
        id: node-modules-cache
        with:
          path: node_modules
          key: node-modules-${{ hashFiles('yarn.lock') }}
      - name: Install
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn affected:test --base=latest --head=HEAD
      - name: e2e
        run: yarn affected:e2e --base=latest --head=HEAD --headless --browser=chrome
      - name: Lint
        run: yarn affected:lint --base=latest --head=HEAD
      - name: Deploy marmicode.io
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          PROJECT: ${{ steps.project.outputs.project }}
        run: tools/deploy.sh $PROJECT
      - uses: pioug/le-slack-message@v1.0.0
        if: failure()
        with:
          JOB: ${{ toJson(job) }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
